<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="ajay-singh-lodhi" failures="1" tests="4" name="ExtentReport.demo" time="0.003" errors="1" timestamp="2021-09-30T18:59:47 IST" skipped="2">
  <testcase classname="ExtentReport.demo" name="doUserReg" time="0.000">
    <skipped/>
  </testcase> <!-- doUserReg -->
  <system-out/>
  <testcase classname="ExtentReport.demo" name="doLogin" time="0.001">
    <error message="Cannot invoke &quot;com.aventstack.extentreports.ExtentReports.createTest(String)&quot; because &quot;this.extent&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.aventstack.extentreports.ExtentReports.createTest(String)" because "this.extent" is null
at ExtentReport.demo.doLogin(demo.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- doLogin -->
  <system-out/>
  <testcase classname="ExtentReport.demo" name="tearDown" time="0.002">
    <failure message="&lt;details&gt;&lt;summary&gt;&lt;b&gt;&lt;font color=red&gt;Exception Occured:Click to see&lt;/font&gt;&lt;/b &gt;&lt;/summary&gt;[ExtentReport.demo.doLogin(demo.java:54)&lt;br&gt; java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&lt;br&gt; java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)&lt;br&gt; java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)&lt;br&gt; java.base/java.lang.reflect.Method.invoke(Method.java:567)&lt;br&gt; org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)&lt;br&gt; org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)&lt;br&gt; org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)&lt;br&gt; org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)&lt;br&gt; org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)&lt;br&gt; org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)&lt;br&gt; org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)&lt;br&gt; org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)&lt;br&gt; java.base/java.util.ArrayList.forEach(ArrayList.java:1511)&lt;br&gt; org.testng.TestRunner.privateRun(TestRunner.java:794)&lt;br&gt; org.testng.TestRunner.run(TestRunner.java:596)&lt;br&gt; org.testng.SuiteRunner.runTest(SuiteRunner.java:377)&lt;br&gt; org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)&lt;br&gt; org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)&lt;br&gt; org.testng.SuiteRunner.run(SuiteRunner.java:276)&lt;br&gt; org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)&lt;br&gt; org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)&lt;br&gt; org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)&lt;br&gt; org.testng.TestNG.runSuitesLocally(TestNG.java:1134)&lt;br&gt; org.testng.TestNG.runSuites(TestNG.java:1063)&lt;br&gt; org.testng.TestNG.run(TestNG.java:1031)&lt;br&gt; org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)&lt;br&gt; org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)&lt;br&gt; org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]&lt;/details&gt; 
" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: <details><summary><b><font color=red>Exception Occured:Click to see</font></b ></summary>[ExtentReport.demo.doLogin(demo.java:54)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br> java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)<br> java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)<br> java.base/java.lang.reflect.Method.invoke(Method.java:567)<br> org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)<br> org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)<br> org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)<br> org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)<br> org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)<br> org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)<br> org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)<br> org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)<br> java.base/java.util.ArrayList.forEach(ArrayList.java:1511)<br> org.testng.TestRunner.privateRun(TestRunner.java:794)<br> org.testng.TestRunner.run(TestRunner.java:596)<br> org.testng.SuiteRunner.runTest(SuiteRunner.java:377)<br> org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)<br> org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)<br> org.testng.SuiteRunner.run(SuiteRunner.java:276)<br> org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br> org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)<br> org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)<br> org.testng.TestNG.runSuitesLocally(TestNG.java:1134)<br> org.testng.TestNG.runSuites(TestNG.java:1063)<br> org.testng.TestNG.run(TestNG.java:1031)<br> org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)<br> org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)<br> org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]</details> 

at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at ExtentReport.demo.tearDown(demo.java:77)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:700)
at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:676)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:660)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- tearDown -->
  <system-out/>
  <testcase classname="ExtentReport.demo" name="isSkip" time="0.000">
    <skipped/>
  </testcase> <!-- isSkip -->
  <system-out/>
</testsuite> <!-- ExtentReport.demo -->
